#sudo: required
dist: xenial
language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - cppcheck
      env: COMPILER=g++-7

jobs:
  include:
    - stage: "Compile"                # Run different code checking in parallel
      name: "cpp Check"
      script:
       - "./build/travis_compile.sh"
       - cppcheck --quiet --force --error-exitcode=1 .
    - stage: "Test"                   # Run different OS tests in parallel
      name: "Ubuntu Unit Test"
      script:
        - "./build/travis_compile.sh"
        - ./bin/UnitTests