#sudo: required
dist: xenial
language: cpp

jobs:
  include:
    - stage: "Static Analysis"                # Run different code checking in parallel
      name: "cppcheck"
      compiler: gcc
      addons:
       apt:
        sources:
         - ubuntu-toolchain-r-test
        packages:
         - g++-7
         - cppcheck
      before_install:
        - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
        - sudo apt-get update -qq
        - sudo apt-get install qt5-default
      script:
       - sudo apt install python3-pip python3-setuptools xutils-dev
       - "travis/linux_conan.sh"
       - mkdir build
       - cd build
       - cmake -DCMAKE_CXX_COMPILER=g++-7 -DCMAKE_C_COMPILER=gcc-7 -DCMAKE_BUILD_TYPE=Debug ..
       - cppcheck --quiet --force --error-exitcode=1 .
    - name: "clang format"
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial
          packages:
            - g++-7
            - clang-format-5.0
      script:
        - sudo apt install python3-pip python3-setuptools xutils-dev
        - "../travis/clang_format.sh"
    - stage: "Test"                   # Run different OS tests in parallel
      name: "Ubuntu Unit Test"
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - cppcheck
      before_install:
        - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
        - sudo apt-get update -qq
        - sudo apt-get install qt5-default
      script:
        - sudo apt install python3-pip python3-setuptools xutils-dev
        - "travis/linux_conan.sh"
        - mkdir build
        - cd build
        - cmake -DCMAKE_CXX_COMPILER=g++-7 -DCMAKE_C_COMPILER=gcc-7 -DCMAKE_BUILD_TYPE=Debug .. && make
        - ./bin/UnitTests
