#sudo: required
dist: xenial
language: cpp

jobs:
  include:
    - stage: "Compile"                # Run different code checking in parallel
      name: "cpp Check"
      compiler: gcc
      addons:
       apt:
        sources:
         - ubuntu-toolchain-r-test
        packages:
         - g++-7
         - cppcheck
      env: COMPILE=g++-7
      script:
       - sudo apt install python3-pip python3-setuptools xutils-dev
       - sudo pip3 install conan
       - conan user
       - conan remote add zimmerk https://api.bintray.com/conan/zimmerk/conan
       - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
       - mkdir -p ~/.conan/profiles
       - cp travis/default ~/.conan/profiles/default
       - mkdir build
       - cd build
       - cmake -DCMAKE_CXX_COMPILER=$COMPILER -DCMAKE_BUILD_TYPE=Debug .. && make
       - cppcheck --quiet --force --error-exitcode=1 .
    - stage: "Test"                   # Run different OS tests in parallel
      name: "Ubuntu Unit Test"
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - cppcheck
      env: COMPILE=g++-7
      script:
        - sudo apt install python3-pip python3-setuptools xutils-dev
        - sudo pip3 install conan
        - conan user
        - conan remote add zimmerk https://api.bintray.com/conan/zimmerk/conan
        - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
        - mkdir -p ~/.conan/profiles
        - cp travis/default ~/.conan/profiles/default
        - mkdir build
        - cd build
        - cmake -DCMAKE_CXX_COMPILER=$COMPILER -DCMAKE_BUILD_TYPE=Debug .. && make
        - cppcheck --quiet --force --error-exitcode=1 .
        - ./bin/UnitTests